### ISSUE TITLE
The label size may have some problems

### ISSUE THREAD

**Issue by chencodeX** [abhaydoke09/Bilinear-CNN-TensorFlow#1]
i use your code to train my data.
1. i use "create_h5_dataset.py" to create my dataset.
2. i user "bcnn_DD_woft.py" to train this data.
then，my computer throws an exception, like this:
Traceback (most recent call last):
  File "bcnn_DD_woft.py", line 369, in <module>
    sess.run(optimizer, feed_dict={imgs: batch_xs, target: batch_ys})
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 944, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (16, 16) for Tensor u'Placeholder_1:0', which has shape '(?, 100)'

I'm curious why my lable size is （16，16），but your code is need input(?,100),maybe i need onehot code？did i need set some parameter when i use “create_h5_dataset.py” to build my dataset?

my train.txt like with you :
/home/meteo/zihao.chen/filter_ext/img_data/67/154.jpg 0
/home/meteo/zihao.chen/filter_ext/img_data/53/123.jpg 1
......
/home/meteo/zihao.chen/filter_ext/img_data/128/6.jpg 99
/home/meteo/zihao.chen/filter_ext/img_data/128/32.jpg 99

I am also 100 class.
i need your help.
thank you !

**Comment by chencodeX** [comment]
i know why!
I do not have enough memory to store so much data，so I split the data into multiple copies of the label,each data label is only about a dozen categories.so ,,, my lable size is （16，16）
