### ISSUE TITLE
bcnn_DD_woft.py error

### ISSUE THREAD

**Issue by MBB001** [abhaydoke09/Bilinear-CNN-TensorFlow#32]
i meet an error：
Data shapes -- (train, val, test) (3300, 488, 488, 3) (330, 224, 224, 3)
Traceback (most recent call last):
  File "bcnn_DD_woft.py", line 286, in <module>
    X_train, Y_train = shuffle(X_train, Y_train)
  File "/home/mb/.local/lib/python2.7/site-packages/tflearn/data_utils.py", line 639, in shuffle
    arrs[i] = np.array(arr)
MemoryError
who can tell me what should i do.       thank you!

**Comment by abhaydoke09** [comment]
@MBB001 

I think you might need to use CPU/GPU with more memory. I trained this model with 24GB GPU memory
