### ISSUE TITLE
bcnn_finetuning.py  gave this error.

### ISSUE THREAD

**Issue by mahfuj9346449** [abhaydoke09/Bilinear-CNN-TensorFlow#8]
Traceback (most recent call last):
  File "bcnn_finetuning.py", line 343, in <module>
    vgg.load_initial_weights(sess)
  File "bcnn_finetuning.py", line 279, in load_initial_weights
    last_layer_weights = np.load('last_layers_epoch_10.npz')
  File "/home/mahfuj/tensorlow-py2/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'last_layers_epoch_10.npz'

**Comment by abhaydoke09** [comment]
Your program could not find the file. Please check the file location or just put the absolute file path.
